import 'package:hajj_urma/widgets/app_bar/custom_app_bar.dart';import 'package:hajj_urma/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:hajj_urma/widgets/custom_icon_button.dart';import 'package:hajj_urma/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:hajj_urma/core/app_export.dart';import 'package:hajj_urma/presentation/confirm_request_bottom_sheet_bottomsheet/confirm_request_bottom_sheet_bottomsheet.dart';class ConfirmRequestScreen extends StatelessWidget {const ConfirmRequestScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.all(24.h), child: Column(children: [_buildConfirm(context), SizedBox(height: 24.v), _buildMightyCincoFamily(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBtn(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeftPrimarycontainer, margin: EdgeInsets.fromLTRB(24.h, 8.v, 311.h, 8.v), onTap: () {onTapArrowLeft(context);}), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildConfirm(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 30.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(10.h), decoration: IconButtonStyleHelper.fillPrimaryTL20, child: CustomImageView(imagePath: ImageConstant.imgCheckmark)), SizedBox(height: 18.v), Text("Request Received!", style: CustomTextStyles.titleMediumBold_1), SizedBox(height: 8.v), SizedBox(width: 278.h, child: RichText(text: TextSpan(children: [TextSpan(text: "We’re checking if the home can be seen on \n", style: CustomTextStyles.titleSmallff74778b), TextSpan(text: "Mon, April 4 4:00 PM", style: CustomTextStyles.titleSmallff16161a), TextSpan(text: " to", style: CustomTextStyles.titleSmallff74778b), TextSpan(text: " "), TextSpan(text: "4:45 PM", style: CustomTextStyles.titleSmallff16161a), TextSpan(text: ".", style: CustomTextStyles.titleSmallff16161aMedium)]), textAlign: TextAlign.center))])); } 
/// Section Widget
Widget _buildMightyCincoFamily(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 21.v), decoration: AppDecoration.outlineGray300.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Container(width: 261.h, margin: EdgeInsets.only(right: 17.h), child: Text("Associate Capital Properties LLC Agent will take you on the tour!", maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.titleSmall!.copyWith(height: 1.50))), SizedBox(height: 9.v), Divider(), SizedBox(height: 11.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgBg48x48, height: 48.adaptSize, width: 48.adaptSize, radius: BorderRadius.circular(24.h), margin: EdgeInsets.only(bottom: 2.v)), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Leslie Alexander", style: CustomTextStyles.titleMediumBold), SizedBox(height: 7.v), Text("Rich Capital Properties LLC", style: CustomTextStyles.titleSmallBluegray500Medium)]), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(top: 14.v, bottom: 16.v))])])); } 
/// Section Widget
Widget _buildBtn(BuildContext context) { return Container(margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 24.v), decoration: AppDecoration.outlineBlueGrayF, child: CustomElevatedButton(text: "Done", onPressed: () {onTapDone(context);})); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 

/// Shows a modal bottom sheet with [ConfirmRequestBottomSheetBottomsheet] 
/// widget content.
/// The sheet is displayed on top of the current view with scrolling enabled if 
/// content exceeds viewport height.
onTapDone(BuildContext context) { showModalBottomSheet(context: context, builder: (_)=>ConfirmRequestBottomSheetBottomsheet(),isScrollControlled: true); } 
 }
