import 'package:hajj_urma/widgets/custom_icon_button.dart';import 'package:hajj_urma/widgets/app_bar/custom_app_bar.dart';import 'package:hajj_urma/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:hajj_urma/widgets/app_bar/appbar_subtitle_two.dart';import 'package:flutter/material.dart';import 'package:hajj_urma/core/app_export.dart';class ProfilePage extends StatelessWidget {const ProfilePage({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.all(24.h), child: Column(children: [SizedBox(height: 70.adaptSize, width: 70.adaptSize, child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgRectangle361, height: 70.adaptSize, width: 70.adaptSize, radius: BorderRadius.circular(35.h), alignment: Alignment.center), CustomIconButton(height: 24.adaptSize, width: 24.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.outlineGrayTL12, alignment: Alignment.bottomRight, onTap: () {onTapBtnTelevision(context);}, child: CustomImageView(imagePath: ImageConstant.imgTelevisionGray50))])), SizedBox(height: 8.v), Text("Cameron Williamson", style: CustomTextStyles.titleMediumBold_1), SizedBox(height: 4.v), Text("hello@gmail.com", style: CustomTextStyles.titleSmallBluegray500Medium), SizedBox(height: 31.v), Align(alignment: Alignment.centerLeft, child: Text("Home search", style: CustomTextStyles.titleSmallBluegray500)), SizedBox(height: 15.v), _buildMyFavorites(context, text: "Recently viewed", onTapMyFavorites: () {onTapMyFavorites(context);}), SizedBox(height: 16.v), _buildMyFavorites(context, text: "My favorites", onTapMyFavorites: () {onTapMyFavorites1(context);}), SizedBox(height: 16.v), _buildMyFavorites(context, text: "Past Tour", onTapMyFavorites: () {onTapMyFavorites2(context);}), SizedBox(height: 32.v), Align(alignment: Alignment.centerLeft, child: Text("General", style: CustomTextStyles.titleSmallBluegray500)), SizedBox(height: 16.v), _buildMyFavorites(context, text: "Sell my home"), SizedBox(height: 16.v), _buildMyFavorites(context, text: "My listings ", onTapMyFavorites: () {onTapMyFavorites3(context);}), SizedBox(height: 16.v), _buildMyFavorites(context, text: "Settings", onTapMyFavorites: () {onTapMyFavorites4(context);}), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeftPrimarycontainer, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "Profile"), styleType: Style.bgFill); } 
/// Common widget
Widget _buildMyFavorites(BuildContext context, {required String text, Function? onTapMyFavorites, }) { return GestureDetector(onTap: () {onTapMyFavorites!.call();}, child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(10.h), decoration: IconButtonStyleHelper.fillGray, child: CustomImageView(imagePath: ImageConstant.imgFavoritePrimary)), Padding(padding: EdgeInsets.only(left: 16.h, top: 12.v, bottom: 7.v), child: Text(text, style: theme.textTheme.titleSmall!.copyWith(color: theme.colorScheme.primaryContainer))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.symmetric(vertical: 10.v))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the editProfileScreen when the action is triggered.
onTapBtnTelevision(BuildContext context) { Navigator.pushNamed(context, AppRoutes.editProfileScreen); } 
/// Navigates to the recentlyViewsScreen when the action is triggered.
onTapMyFavorites(BuildContext context) { Navigator.pushNamed(context, AppRoutes.recentlyViewsScreen); } 
/// Navigates to the favoriteScreen when the action is triggered.
onTapMyFavorites1(BuildContext context) { Navigator.pushNamed(context, AppRoutes.favoriteScreen); } 
/// Navigates to the pastToursScreen when the action is triggered.
onTapMyFavorites2(BuildContext context) { Navigator.pushNamed(context, AppRoutes.pastToursScreen); } 
/// Navigates to the homeListingScreen when the action is triggered.
onTapMyFavorites3(BuildContext context) { Navigator.pushNamed(context, AppRoutes.homeListingScreen); } 
/// Navigates to the settingsScreen when the action is triggered.
onTapMyFavorites4(BuildContext context) { Navigator.pushNamed(context, AppRoutes.settingsScreen); } 
 }
