import 'package:hajj_urma/widgets/custom_icon_button.dart';import 'package:hajj_urma/widgets/custom_elevated_button.dart';import 'widgets/confirmrequestgrid_item_widget.dart';import 'package:flutter/material.dart';import 'package:hajj_urma/core/app_export.dart';class ConfirmRequestBottomSheetBottomsheet extends StatelessWidget {const ConfirmRequestBottomSheetBottomsheet({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 8.v), decoration: AppDecoration.fillGray50.copyWith(borderRadius: BorderRadiusStyle.customBorderTL20), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(width: 56.h, child: Divider(color: appTheme.blueGray500)), SizedBox(height: 8.v), _buildHeaderRow(context), SizedBox(height: 24.v), _buildAgentNameRow(context), SizedBox(height: 25.v), Container(width: 320.h, margin: EdgeInsets.only(left: 24.h, right: 29.h), child: RichText(text: TextSpan(children: [TextSpan(text: "My associate Rachel will take you to see the home on ", style: CustomTextStyles.bodyMediumff16161a), TextSpan(text: "Mon, April 4 4:00 PM", style: CustomTextStyles.titleSmallff16161a), TextSpan(text: " to ", style: CustomTextStyles.bodyMediumff16161a), TextSpan(text: "4:45 PM. I will follow up afterwards with you to see how it went.", style: CustomTextStyles.titleSmallff16161a)]), textAlign: TextAlign.left)), SizedBox(height: 15.v), Container(width: 324.h, margin: EdgeInsets.symmetric(horizontal: 24.h), child: Text("If you’d like to keep working with me after your tour, I’ll be here for you every step of the way - from finding the right home to writing a winning offer.", maxLines: 3, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumPrimaryContainer.copyWith(height: 1.50))), SizedBox(height: 21.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("About Me", style: CustomTextStyles.titleMediumBold_1))), SizedBox(height: 13.v), Container(width: 325.h, margin: EdgeInsets.symmetric(horizontal: 24.h), child: RichText(text: TextSpan(children: [TextSpan(text: "Diana", style: CustomTextStyles.titleSmallff16161a), TextSpan(text: " "), TextSpan(text: "Richards", style: CustomTextStyles.titleSmallff16161a), TextSpan(text: " is a third-generation realtor and Bay Area native who has lived in  LA since 2015. She guides her clients through the City and... ", style: CustomTextStyles.bodyMediumff16161a), TextSpan(text: "More", style: CustomTextStyles.titleSmallff1786f9)]), textAlign: TextAlign.left)), SizedBox(height: 23.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 24.h), child: Text("Highlights", style: CustomTextStyles.titleMediumBold_1))), SizedBox(height: 13.v), _buildConfirmRequestGrid(context), SizedBox(height: 24.v)])); } 
/// Section Widget
Widget _buildHeaderRow(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 8.v), decoration: AppDecoration.fillGray50, child: Row(children: [CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(8.h), onTap: () {onTapBtnIcon(context);}, child: CustomImageView(imagePath: ImageConstant.imgIconPrimarycontainer)), Padding(padding: EdgeInsets.only(left: 67.h, top: 10.v, bottom: 4.v), child: Text("Agent Detail", style: theme.textTheme.titleMedium))])); } 
/// Section Widget
Widget _buildAgentNameRow(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgBg60x60, height: 60.adaptSize, width: 60.adaptSize, radius: BorderRadius.circular(30.h)), Padding(padding: EdgeInsets.only(left: 11.h, top: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Leslie Alexander", style: CustomTextStyles.titleMediumBold), SizedBox(height: 11.v), Text("Rich Capital Properties LLC", style: CustomTextStyles.titleSmallBluegray500Medium)])), CustomElevatedButton(height: 26.v, width: 74.h, text: "4.8(9)", margin: EdgeInsets.only(left: 4.h, top: 4.v, bottom: 30.v), leftIcon: Container(margin: EdgeInsets.only(right: 4.h), child: CustomImageView(imagePath: ImageConstant.imgSignalYellow700, height: 16.adaptSize, width: 16.adaptSize)), buttonStyle: CustomButtonStyles.fillGrayTL13, buttonTextStyle: CustomTextStyles.labelMediumOnPrimary)])); } 
/// Section Widget
Widget _buildConfirmRequestGrid(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 65.v, crossAxisCount: 2, mainAxisSpacing: 13.h, crossAxisSpacing: 13.h), physics: NeverScrollableScrollPhysics(), itemCount: 4, itemBuilder: (context, index) {return ConfirmrequestgridItemWidget();})); } 

/// Navigates back to the previous screen.
onTapBtnIcon(BuildContext context) { Navigator.pop(context); } 
 }
